### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by in4mation-hub** [extraevents/extraevents.org#1]
how do i set this up at my site  because i want to create a site like this, how do i set it up?

**Comment by suphair** [comment]
Why do it?
I see no reason to create something similar to our site.

**Comment by in4mation-hub** [comment]
i want to create something like your site, i want to make a site with more events and create competitions, i already have a site but it sucks, could you please help me make something like your site?

**Comment by in4mation-hub** [comment]
WHY DID U CLOSE IT

**Comment by in4mation-hub** [comment]
FIRST OF ALL IT IS RUDE TO CLOSE IT WITHOUT GIVING ME AN ANSWER!
SECOND I ONLY ASKED HOW  DO I MAKE A SITE LIKE YOURS NOT COPY YOUR SITE!
